In [18]:
import numpy as np

In [19]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [20]:
np.array(my_list)

array([1, 2, 3])

In [22]:
type(my_list)

list

In [24]:
type(np.array(my_list))

numpy.ndarray

In [26]:
a = np.array(my_list)

In [27]:
a

array([1, 2, 3])

In [32]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
b = np.array(my_matrix)

In [33]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.array(list(range(1,10)))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [39]:
np.arange(0, 11, 2, dtype=float)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [40]:
np.zeros(3)

array([0., 0., 0.])

In [44]:
np.zeros((5,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
np.linspace(50, 70, 80)

array([50.        , 50.25316456, 50.50632911, 50.75949367, 51.01265823,
       51.26582278, 51.51898734, 51.7721519 , 52.02531646, 52.27848101,
       52.53164557, 52.78481013, 53.03797468, 53.29113924, 53.5443038 ,
       53.79746835, 54.05063291, 54.30379747, 54.55696203, 54.81012658,
       55.06329114, 55.3164557 , 55.56962025, 55.82278481, 56.07594937,
       56.32911392, 56.58227848, 56.83544304, 57.08860759, 57.34177215,
       57.59493671, 57.84810127, 58.10126582, 58.35443038, 58.60759494,
       58.86075949, 59.11392405, 59.36708861, 59.62025316, 59.87341772,
       60.12658228, 60.37974684, 60.63291139, 60.88607595, 61.13924051,
       61.39240506, 61.64556962, 61.89873418, 62.15189873, 62.40506329,
       62.65822785, 62.91139241, 63.16455696, 63.41772152, 63.67088608,
       63.92405063, 64.17721519, 64.43037975, 64.6835443 , 64.93670886,
       65.18987342, 65.44303797, 65.69620253, 65.94936709, 66.20253165,
       66.4556962 , 66.70886076, 66.96202532, 67.21518987, 67.46

In [57]:
np.random.rand(5)

array([0.44994179, 0.54521519, 0.1569545 , 0.0968948 , 0.99271449])

Goal: random numbers from -3 to 3

In [63]:
np.random.rand(15) * 6

array([4.08351551, 3.75422749, 4.91280275, 2.19471976, 3.75707788,
       0.5596725 , 2.28988887, 5.64087662, 3.37119928, 3.38236895,
       1.1360853 , 4.94559778, 0.67803249, 0.57399176, 4.39091447])

In [64]:
np.random.rand(15) * 6 - 3

array([-2.20117072,  0.32039279, -1.85246816,  0.44966708,  2.97253593,
        0.28725498,  0.55334384, -0.28994139, -1.73824563,  1.09636064,
       -2.30112391,  1.89443348,  2.35392678, -2.3385675 , -0.6012986 ])

In [69]:
np.random.rand(15) * 2 + 3

array([4.60390989, 4.30385455, 4.44849756, 4.33775625, 4.33592987,
       4.97655691, 3.81165255, 3.10573455, 3.74079666, 3.02333901,
       4.26010269, 4.53725826, 4.81777593, 4.63073522, 3.19011367])

In [67]:
np.random.randn(10)

array([ 0.64481445, -1.78616646,  0.55164969,  1.36830402,  0.37813596,
        0.19563561, -1.61469516,  0.22588421, -0.29742636, -2.20170826])

In [72]:
def randab(a, b, n):
    return np.random.rand(n) * (b-a) + a

In [73]:
randab(80, 90, 10)

array([80.09003309, 82.14506742, 80.64424886, 83.65009771, 84.45672656,
       82.29674661, 89.92386314, 84.92931289, 83.94400892, 82.2324083 ])

In [76]:
np.random.randint(100, 200, size=10) / 10

array([11.4, 13.8, 15.5, 12.3, 10.5, 14. , 12.3, 18.8, 11.7, 19.9])

In [77]:
a = np.arange(100)

In [78]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [79]:
a.shape

(100,)

In [84]:
a = np.ones((5,6))

In [85]:
a.shape

(5, 6)

In [88]:
a.reshape(6,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
a = np.arange(100)

In [90]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [94]:
a.reshape(5,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [93]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [97]:
a = (np.random.rand(25) * 10).reshape(5,5)

In [98]:
a

array([[5.825519  , 4.95109568, 4.6048206 , 4.96547624, 1.45125378],
       [1.33771537, 6.92915001, 4.79263459, 8.90216774, 9.74886997],
       [6.70875731, 6.79431613, 3.7311359 , 1.67873573, 0.94028695],
       [9.11212909, 6.2257898 , 1.75342215, 1.99034354, 3.69390615],
       [3.66176663, 8.5766128 , 6.43440934, 7.94945929, 8.55694366]])

In [99]:
a.min()

0.9402869469869835

In [102]:
a.argmin()

14

In [103]:
a.shape

(5, 5)

In [105]:
a.dtype

dtype('float64')

In [106]:
type(a)

numpy.ndarray

In [110]:
a.astype(int)[0][0] = 0

In [112]:
a

array([[5.825519  , 4.95109568, 4.6048206 , 4.96547624, 1.45125378],
       [1.33771537, 6.92915001, 4.79263459, 8.90216774, 9.74886997],
       [6.70875731, 6.79431613, 3.7311359 , 1.67873573, 0.94028695],
       [9.11212909, 6.2257898 , 1.75342215, 1.99034354, 3.69390615],
       [3.66176663, 8.5766128 , 6.43440934, 7.94945929, 8.55694366]])

In [113]:
a.astype(int)

array([[5, 4, 4, 4, 1],
       [1, 6, 4, 8, 9],
       [6, 6, 3, 1, 0],
       [9, 6, 1, 1, 3],
       [3, 8, 6, 7, 8]])

In [114]:
arr = np.arange(0,11)

In [115]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr[8]

8

In [118]:
arr[-1]

10

In [119]:
arr[1:5]

array([1, 2, 3, 4])

In [120]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [121]:
arr[:5]

array([0, 1, 2, 3, 4])

In [124]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [128]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [131]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [132]:
arr[9:2:-1]

array([9, 8, 7, 6, 5, 4, 3])

In [133]:
arr[1:9:-1]

array([], dtype=int64)

### Broadcasting 

In [134]:
arr[0:5] = 100

In [135]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [136]:
b = arr[0:5]

In [137]:
b[:] = 99

In [138]:
b

array([99, 99, 99, 99, 99])

In [139]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [140]:
b = arr[0:5].copy()

In [141]:
b

array([99, 99, 99, 99, 99])

In [142]:
b[:] = 77

In [143]:
b

array([77, 77, 77, 77, 77])

In [144]:
a

array([[5.825519  , 4.95109568, 4.6048206 , 4.96547624, 1.45125378],
       [1.33771537, 6.92915001, 4.79263459, 8.90216774, 9.74886997],
       [6.70875731, 6.79431613, 3.7311359 , 1.67873573, 0.94028695],
       [9.11212909, 6.2257898 , 1.75342215, 1.99034354, 3.69390615],
       [3.66176663, 8.5766128 , 6.43440934, 7.94945929, 8.55694366]])

In [145]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [146]:
a

array([[5.825519  , 4.95109568, 4.6048206 , 4.96547624, 1.45125378],
       [1.33771537, 6.92915001, 4.79263459, 8.90216774, 9.74886997],
       [6.70875731, 6.79431613, 3.7311359 , 1.67873573, 0.94028695],
       [9.11212909, 6.2257898 , 1.75342215, 1.99034354, 3.69390615],
       [3.66176663, 8.5766128 , 6.43440934, 7.94945929, 8.55694366]])

In [147]:
a[2][1]

6.794316132476519

In [148]:
a[2,1]

6.794316132476519

In [162]:
a[[0,2,4],:][:,[2,3]]

array([[4.6048206 , 4.96547624],
       [3.7311359 , 1.67873573],
       [6.43440934, 7.94945929]])

In [184]:
a = np.arange(1,11)*100

In [185]:
a

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [186]:
f = [False, True, False, False, True, False, False, True, True, False]

In [187]:
a[f]

array([200, 500, 800, 900])

In [188]:
f = a>3
a[f]

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [189]:
(a<3).dtype

dtype('bool')

In [190]:
a[a<3]

array([], dtype=int64)

In [200]:
a[((a < 300) | (a > 700))]

array([ 100,  200,  800,  900, 1000])

In [201]:
a[300:700]

array([], dtype=int64)

In [202]:
a = np.random.rand(100).reshape(2,5,10)

In [203]:
a

array([[[0.68067247, 0.01458852, 0.38683643, 0.04694905, 0.99098957,
         0.39261303, 0.52648965, 0.26781824, 0.08412437, 0.0345351 ],
        [0.68679798, 0.78816692, 0.28208533, 0.13212806, 0.57656339,
         0.63502805, 0.98894045, 0.29515626, 0.3453526 , 0.01722287],
        [0.41133813, 0.0443058 , 0.70077631, 0.7443598 , 0.70178762,
         0.20497947, 0.21006685, 0.96224826, 0.04684478, 0.2036211 ],
        [0.30257375, 0.4674227 , 0.29051425, 0.7094472 , 0.87174927,
         0.24786865, 0.99164853, 0.6511819 , 0.56216843, 0.8467736 ],
        [0.12665225, 0.20911891, 0.93590813, 0.46380998, 0.01221281,
         0.45404324, 0.23179949, 0.95328792, 0.32892936, 0.95166868]],

       [[0.21153432, 0.7463665 , 0.51107317, 0.77665362, 0.25270281,
         0.49853865, 0.39567592, 0.26804127, 0.49763087, 0.01378156],
        [0.63849645, 0.74418346, 0.55591561, 0.41442174, 0.18208898,
         0.97064373, 0.78250881, 0.57667465, 0.74520624, 0.17424617],
        [0.64054373, 0.81

In [204]:
a.shape

(2, 5, 10)

In [206]:
a[a>0.5].shape

(44,)

In [209]:
a[1][1][a[1][1]>0.5]

array([0.63849645, 0.74418346, 0.55591561, 0.97064373, 0.78250881,
       0.57667465, 0.74520624])

In [216]:
a = np.array([1,2,3])
b = np.array([3,4,5])

In [217]:
a+b

array([4, 6, 8])

In [218]:
a*b

array([ 3,  8, 15])

In [219]:
a/b

array([0.33333333, 0.5       , 0.6       ])

In [220]:
a+4

array([5, 6, 7])

In [221]:
1/a

array([1.        , 0.5       , 0.33333333])

In [222]:
a ** 3

array([ 1,  8, 27])

In [223]:
a

array([1, 2, 3])

In [230]:
np.concatenate((a,b))

array([1, 2, 3, 3, 4, 5])

In [227]:
a

array([1, 2, 3])

In [231]:
np.sort(a)

array([1, 2, 3])

In [232]:
sorted(a)

[1, 2, 3]

In [233]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [234]:
np.max(a)

3

In [235]:
a.max()

3

In [236]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [237]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])